### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by ljsebald** [usnistgov/blossom-sam#3]
# User Story:

The software asset management system will need to include an installer component that is used to install software and register it back to the web service that communicates with the blossom chaincode to. This installer should ideally be simple and adaptable and be able to grab keys from the web service.

## Goals:

The installer should be able to take an input zip file and follow the manifest to install the application. It should then generate a SWID tag for the application and communicate that to the web service for the software asset management system. If a key is needed to activate the program, it should request this from the software asset management system and wait for the key to be returned. Upon retrieving the key, the key should be installed wherever it is required for the application.

## Dependencies:

- [x] The installer manifest format must be developed before the installer can be completed. ( #2 )
- [ ] A skeleton of the web service is required for installer communication ( #4 )

## Acceptance Criteria

- [ ] Parsing a zip file and extracting the program and manifest
- [ ] Parsing installer manifest file
- [ ] Following the manifest to install the software
- [ ] Retrieving a key from the SAM web service

**Comment by SamuelHoward** [comment]
Currently working on the `installer` branch to resolve this issue. This branch is able to extract a program and manifest from a zip file, parse the manifest, and install the software. It does not yet interact with the web service. I will make a PR once this installer branch does accurately interact with the web service.
